steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: [ '-c', 'ls -la']
  dir: core/java/iesi-core
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['test']
  dir: core/java/iesi-core
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']
  dir: core/java/iesi-core