steps:
- name: maven:3-jdk-8
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    mvn install:install-file -Dfile=../../../build/ext/xeger-1.0.jar -DgroupId=nl.flotsam -DartifactId=xeger -Dversion=1.0 -Dpackaging=jar \
    && mvn install:install-file -Dfile=../../../build/ext/artifactory-java-client-api-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=api -Dversion=2.6.0 -Dpackaging=jar \
    && mvn install:install-file -Dfile=../../../build/ext/artifactory-java-client-httpClient-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=httpClient -Dversion=2.6.0 -Dpackaging=jar \
    && mvn install:install-file -Dfile=../../../build/ext/artifactory-java-client-ning-services-2.5.1.jar -DgroupId=artifactory-java-client -DartifactId=ning-services -Dversion=2.5.1 -Dpackaging=jar \
    && mvn install:install-file -Dfile=../../../build/ext/artifactory-java-client-services-2.6.0.jar -DgroupId=artifactory-java-client -DartifactId=services -Dversion=2.6.0 -Dpackaging=jar \
    && mvn test \
    && mvn -Dmaven.test.skip=true -P dependencies install project-info-reports:dependencies \
    && mkdir -p ../iesi-rest-without-microservices/run/cache \
    && mkdir -p ../iesi-rest-without-microservices/metadata/gen \
    && mvn -f ../iesi-rest-without-microservices test \
    && mvn -f ../iesi-rest-without-microservices -Dmaven.test.skip=true -P package project-info-reports:dependencies
  dir: core/java/iesi-core
